version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/raidhelper
    depends_on:
      - postgres
    networks:
      - main
  postgres:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5400:5432
    networks:
      - main
    environment:
      POSTGRES_DB: raidhelper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  postgres_volume:

networks:
  main:
    driver: bridge